apiVersion: v1
kind: Secret
metadata:
    name: kite-secrets
    namespace: kube-system
type: Opaque
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:WoPuPEFJWHTHJFJs3KBgBRIKVFqBqbmSQAmuNZsMKi3z1yMy+vg0zw==,iv:tyM9K76XzPHW7upUH6TfPfXW3ONzphhusOl0f22UxhI=,tag:Zw1UZhj01fD2aA8Bf9UVOg==,type:str]
    KITE_ENCRYPT_KEY: ENC[AES256_GCM,data:XgVn3bUvJfciKRhC6ujSk216xFcmSqbdB88K1kDEjqCTpSLZUu/J+A==,iv:W5gVMUfKNwNzNqo5jq1BAATchbLFuTA5nJfbn503D0A=,tag:ZuE2pYnoirs6cYBK4G0o9g==,type:str]
    DB_TYPE: ENC[AES256_GCM,data:ngAQVNRn,iv:vCRhzAh0Y/4VrNjUc8AlF0BF6ebgmlkamAgpYyjHktA=,tag:h5tKtbSdUK9hZvsLTCv08A==,type:str]
    KITE_USERNAME: ENC[AES256_GCM,data:ZsUeTNpREUKF,iv:WSZ/ucaJ38iZpUmKMpiXIM2XYY+h1hMMGlNOAUjdNzA=,tag:Rtnw7DnUh39cH4K3y4tjRA==,type:str]
    KITE_PASSWORD: ENC[AES256_GCM,data:mizy3SN2Va4VsDMFi080jWDuuiQrHdWjVe3jRszi,iv:2L6iz6BGiFI5jO40I3Cb0lVCDpk+XVoTRG8WiL8krJ0=,tag:OQiEQEegK0HDyBI8rQH8zg==,type:str]
sops:
    age:
        - recipient: age1cs0csgzz7xtc644my5r9ee0uy8s6zx3njnymwd32g8rwcamqzges8pds9a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKMzdyNWlPcHhoandta1A4
            dGVObHpFOW9iN1NVT200Q3JGRDg5bW5aSHdZCkRabmhnVlFaalVJQ2ZSRWNWYktx
            Zkh3UGp0dTZMVkduU2hxS1R3RHBTM0kKLS0tIE9uNGlwSHF4QnJraGZVRmt3QkVo
            alU2ck5mMzdkVmJWMlo0ZTdMWFdKTlEKdCgyxjz7HyjcZcSeTjcKrxySnbI53alj
            5kZu6Ts45j38R/+9aSbbdlIY+BdsdJT/G8xSuVboXNvZOOncIzxDsw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cuuzzp3fu0g62hdpgszw4ce9ndpk4zgaxaj8x3s0u00kq9xmnp6qq7547k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNazBlSmwwNzVBSm1oYTI5
            NnJxQ2pWa3JCMWxqYmQ5ZWZFTlMzdDZraVU4CnVTR21aZE9DZjErbEp4L3NtSHlp
            WStjdm1LRTZBdVE2eG1JbGFaNWZ4Z0UKLS0tIGprcXFIQnZsTVR1OWJ4UnQxWTEr
            RUx5THMvSnA0UGJBWHhVOVZvUzBiVkUKbo3+cKHTCI5OcJiULHnmtkrdLlbanE4g
            1OeOjYzy+A7Hzx25nMHFdNTBCUgkaa6oQ8ZvFRm5wk2k2tLQxpU0Tw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age179xlc7hrhzlzjatrfjr5a5puldkxqzar7k36409w2dxhh9rxr42q2745tl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnUHhaVWRaRGxqUmc5cEc4
            L2NFaHJZTGpPQkNWV3FuZmMwZnlqWFRsRmpjCjdzdFJ1OE1mN2pydmRXY2xBbVpO
            b3FPUVdESklXa21oWnNvazFOSEVVRTgKLS0tIFVqR2RFOVNrcmlzVXBKTVhLUlZP
            VmQwTUtubnVXVWsxU0xLSTFaSHVaNmcKomIiLEb38GhfwAyEDIELNfgdgDU1aUgz
            rcOywl0ZJpozV2sEIrjyrZ3RwvCKzXPuZzp9q2GTbxns2GPnaiaZkQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xk55pvdly05kxl5sxgt4vmczalyw4vmzyrehg5ttqcjz8acvvg5s6nyval
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRFpvdUlnOCtRVU5TcGdK
            VVB2MGxtNU1GQ2FETERGUlA4V3RneGxzL3pNCkpvR0krcWh3WG4xdHhYQ2gxaCto
            NVVkZEtFQllwN2g3RlpSRy80Y0V4TUUKLS0tIFUwcUtUUEQ5T0VYdHJ5MjNYZGo3
            OEZMaVhYYVdkQmNZY3ZIZENkWjNSSG8KF3kO7VLWpOKOWaz9oZ9lPkQX77+eLz6Q
            mby/IJQZAF/4z9j909a72A2fs6q6h+h+Yhra7EcJDuH/yGUOEnILsA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k3djrwgz90hpanec67jq0dz40apha5rujya9tvn6zdt7mhg9z9gsuy8wrw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0a3JQZnUraEdGTkdVbFla
            Njk1SG9sK1R0TGFDZkptUUlYdjJFd3liQ1c0CnJ1OCtocmVVZnpUdnFVTkZEclBr
            WG16RU9ONVUyUnRuVFVyNU41NVZQMFEKLS0tIFlxNWorenYwdmhLQ2o4cWFYZXBw
            eHVkYmMyT2NPamQxOENTYzRoeFpkSmcKUojLZmUQi5r+dGgHyVSrpCn7h2i16Vv9
            QbzRmgaF47Xb7f9mrx4DYoE5PipiljuLmnlg2m7m5ubHfupZPNPZiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-31T17:43:14Z"
    mac: ENC[AES256_GCM,data:AC88UgMs8fr6yJob1Oqbt9bxCrFiYCP+0aNchwIDzeMeDO4AF0puqSqrpTa9f2M6RL3F8Y9rB/4CY+ArCL27oGAg2eQUAnglk5+B9m0G0uwNrTdoC+X0WsTS30ZWHym4mS5OPiqfE2OIoYVPKNVrOyJnRz3VOI7S8Cq9jZiv5bA=,iv:nCJnVf91jCiWiuIARwd4jB1FmyVf9prcCQZBaC17SXE=,tag:uB2LK/ua5gKobfr6k4gX4w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
