// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: jobs.proto

package jobs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobType int32

const (
	JobType_UNKNOWN_TYPE JobType = 0
	JobType_RESIZE       JobType = 1
	JobType_GRAYSCALE    JobType = 2
	JobType_BLUR         JobType = 3
	JobType_RECONSTRUCT  JobType = 4
)

// Enum value maps for JobType.
var (
	JobType_name = map[int32]string{
		0: "UNKNOWN_TYPE",
		1: "RESIZE",
		2: "GRAYSCALE",
		3: "BLUR",
		4: "RECONSTRUCT",
	}
	JobType_value = map[string]int32{
		"UNKNOWN_TYPE": 0,
		"RESIZE":       1,
		"GRAYSCALE":    2,
		"BLUR":         3,
		"RECONSTRUCT":  4,
	}
)

func (x JobType) Enum() *JobType {
	p := new(JobType)
	*p = x
	return p
}

func (x JobType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobType) Descriptor() protoreflect.EnumDescriptor {
	return file_jobs_proto_enumTypes[0].Descriptor()
}

func (JobType) Type() protoreflect.EnumType {
	return &file_jobs_proto_enumTypes[0]
}

func (x JobType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobType.Descriptor instead.
func (JobType) EnumDescriptor() ([]byte, []int) {
	return file_jobs_proto_rawDescGZIP(), []int{0}
}

type JobStatus int32

const (
	JobStatus_PENDING     JobStatus = 0
	JobStatus_IN_PROGRESS JobStatus = 1
	JobStatus_COMPLETED   JobStatus = 2
	JobStatus_FAILED      JobStatus = 3
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "PENDING",
		1: "IN_PROGRESS",
		2: "COMPLETED",
		3: "FAILED",
	}
	JobStatus_value = map[string]int32{
		"PENDING":     0,
		"IN_PROGRESS": 1,
		"COMPLETED":   2,
		"FAILED":      3,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_jobs_proto_enumTypes[1].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_jobs_proto_enumTypes[1]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_jobs_proto_rawDescGZIP(), []int{1}
}

type Region struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Region) Reset() {
	*x = Region{}
	mi := &file_jobs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Region) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Region) ProtoMessage() {}

func (x *Region) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Region.ProtoReflect.Descriptor instead.
func (*Region) Descriptor() ([]byte, []int) {
	return file_jobs_proto_rawDescGZIP(), []int{0}
}

func (x *Region) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Region) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Region) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Region) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type Job struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type              JobType                `protobuf:"varint,2,opt,name=type,proto3,enum=jobs.JobType" json:"type,omitempty"`
	Status            JobStatus              `protobuf:"varint,3,opt,name=status,proto3,enum=jobs.JobStatus" json:"status,omitempty"`
	OriginalImagePath string                 `protobuf:"bytes,4,opt,name=original_image_path,json=originalImagePath,proto3" json:"original_image_path,omitempty"`
	ResultImagePath   string                 `protobuf:"bytes,5,opt,name=result_image_path,json=resultImagePath,proto3" json:"result_image_path,omitempty"`
	ParentId          string                 `protobuf:"bytes,6,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Region            *Region                `protobuf:"bytes,7,opt,name=region,proto3" json:"region,omitempty"`
	Attempts          int32                  `protobuf:"varint,8,opt,name=attempts,proto3" json:"attempts,omitempty"`
	CreatedAt         int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Parameters        map[string]string      `protobuf:"bytes,10,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_jobs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_jobs_proto_rawDescGZIP(), []int{1}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetType() JobType {
	if x != nil {
		return x.Type
	}
	return JobType_UNKNOWN_TYPE
}

func (x *Job) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_PENDING
}

func (x *Job) GetOriginalImagePath() string {
	if x != nil {
		return x.OriginalImagePath
	}
	return ""
}

func (x *Job) GetResultImagePath() string {
	if x != nil {
		return x.ResultImagePath
	}
	return ""
}

func (x *Job) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Job) GetRegion() *Region {
	if x != nil {
		return x.Region
	}
	return nil
}

func (x *Job) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *Job) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Job) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

var File_jobs_proto protoreflect.FileDescriptor

const file_jobs_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"jobs.proto\x12\x04jobs\"R\n" +
	"\x06Region\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\"\xb5\x03\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\x04type\x18\x02 \x01(\x0e2\r.jobs.JobTypeR\x04type\x12'\n" +
	"\x06status\x18\x03 \x01(\x0e2\x0f.jobs.JobStatusR\x06status\x12.\n" +
	"\x13original_image_path\x18\x04 \x01(\tR\x11originalImagePath\x12*\n" +
	"\x11result_image_path\x18\x05 \x01(\tR\x0fresultImagePath\x12\x1b\n" +
	"\tparent_id\x18\x06 \x01(\tR\bparentId\x12$\n" +
	"\x06region\x18\a \x01(\v2\f.jobs.RegionR\x06region\x12\x1a\n" +
	"\battempts\x18\b \x01(\x05R\battempts\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x129\n" +
	"\n" +
	"parameters\x18\n" +
	" \x03(\v2\x19.jobs.Job.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*Q\n" +
	"\aJobType\x12\x10\n" +
	"\fUNKNOWN_TYPE\x10\x00\x12\n" +
	"\n" +
	"\x06RESIZE\x10\x01\x12\r\n" +
	"\tGRAYSCALE\x10\x02\x12\b\n" +
	"\x04BLUR\x10\x03\x12\x0f\n" +
	"\vRECONSTRUCT\x10\x04*D\n" +
	"\tJobStatus\x12\v\n" +
	"\aPENDING\x10\x00\x12\x0f\n" +
	"\vIN_PROGRESS\x10\x01\x12\r\n" +
	"\tCOMPLETED\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03B1Z/github.com/christianmz565/microphoto/proto/jobsb\x06proto3"

var (
	file_jobs_proto_rawDescOnce sync.Once
	file_jobs_proto_rawDescData []byte
)

func file_jobs_proto_rawDescGZIP() []byte {
	file_jobs_proto_rawDescOnce.Do(func() {
		file_jobs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jobs_proto_rawDesc), len(file_jobs_proto_rawDesc)))
	})
	return file_jobs_proto_rawDescData
}

var file_jobs_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_jobs_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_jobs_proto_goTypes = []any{
	(JobType)(0),   // 0: jobs.JobType
	(JobStatus)(0), // 1: jobs.JobStatus
	(*Region)(nil), // 2: jobs.Region
	(*Job)(nil),    // 3: jobs.Job
	nil,            // 4: jobs.Job.ParametersEntry
}
var file_jobs_proto_depIdxs = []int32{
	0, // 0: jobs.Job.type:type_name -> jobs.JobType
	1, // 1: jobs.Job.status:type_name -> jobs.JobStatus
	2, // 2: jobs.Job.region:type_name -> jobs.Region
	4, // 3: jobs.Job.parameters:type_name -> jobs.Job.ParametersEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_jobs_proto_init() }
func file_jobs_proto_init() {
	if File_jobs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jobs_proto_rawDesc), len(file_jobs_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jobs_proto_goTypes,
		DependencyIndexes: file_jobs_proto_depIdxs,
		EnumInfos:         file_jobs_proto_enumTypes,
		MessageInfos:      file_jobs_proto_msgTypes,
	}.Build()
	File_jobs_proto = out.File
	file_jobs_proto_goTypes = nil
	file_jobs_proto_depIdxs = nil
}
