apiVersion: v1
kind: Secret
metadata:
    name: grafana-secrets
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:FLPcocTCmWN9,iv:udn6s2wzGfOX/Ooxw74Ue9M/opvq8kIU42KPNrO3/cU=,tag:qj9Y+46OJaQxY/T0nPbiWQ==,type:str]
    admin-password: ENC[AES256_GCM,data:/usNGeYJFp3BIi80/EABxAuuaG/IooK/u7R59MBQhmWaC+QCOxPD/Qta0Q==,iv:G/IJs1R73f5Mn4tBazQ4RMBqVH0iAlnWZOtbESagnwU=,tag:fvg6OCnUcBSTF1G9i1Lcmw==,type:str]
sops:
    age:
        - recipient: age1cs0csgzz7xtc644my5r9ee0uy8s6zx3njnymwd32g8rwcamqzges8pds9a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQlYrVDBTZnF1UmRHY3FB
            SFhVQXk4MU0xN3IvRjR0aVlFaFg4UkpTUFY0CmZJWWdheEpRY3BjeU9mMGxvTHVZ
            QzBzbHh2WUNWQXJ6VDZBN3BxSEhzUjAKLS0tIDdHWThOZDkyY1NQVjd6cFZEdlV3
            QXZ0VFNxaENoQ3JhYWVKU1VxQ1pkaGMKFyEnIwpfHHt8Kj032Ku7CNgyJvVUS5WE
            FbYGX5iwJ7hKIcDk1+OPhqcIDNek/KqjFAOorLBPgm7ek3d2RmA09w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cuuzzp3fu0g62hdpgszw4ce9ndpk4zgaxaj8x3s0u00kq9xmnp6qq7547k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydU9hRlIrRi92bzVKVnZw
            aDZiNHQ5aS8vVGUxblF0L3gzdTNLZFJlSEhrCkVWeWRGcmhYZDF4MVpya0FvMjYv
            QWJuTTkwdEpXTk1IYjFqMStjU21XWVkKLS0tIDluNkFpcUVreGJvOVErMWxkWjhl
            eGNxN25WOHVHZFBTTjRLbDFjQjIyQW8KzNrYnaU2SIrOk77HjhCtEtya6TQHDVDS
            k8XUTFlHlEYgitaKWWdddElEbK5FjX4BUJWGjUACLuJwGTgK5BApow==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age179xlc7hrhzlzjatrfjr5a5puldkxqzar7k36409w2dxhh9rxr42q2745tl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUm5mUlZlRnRHM0xRSFpi
            c1UxYlZIcWw0Nmx5OFdwTHJEVThMRld0dW40CkpxMVdhaUxRR2NOQ2dsbXVHaFQz
            RUtSTXJuWGVkYS9EUVRhL1RKU2dtREkKLS0tIEFjNTgyNklNeHN5TE5uenFRVmpy
            WGY3ZkVFM1NPVTNVOXlTRUpXMHk5RncKcUxf2q5hykRmHCDlXxO3Ha9NzxK641Lq
            2ioKncJts2LNbgpDkWfhpzc8ZZcLlquKhmaYwNK7q+VBXU7CpMbC7A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xk55pvdly05kxl5sxgt4vmczalyw4vmzyrehg5ttqcjz8acvvg5s6nyval
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzbVZNWVVpT1RadE9CQTlt
            TEVYcHliSUlWYVNTL2lWRDF0bzdId2IxTlZRCkVnUVR3RVVIMG54OUZoMUp4S3dJ
            eVJtb0Z4b20ydyt2WkFkRDJqNFpEY28KLS0tIDZkOHczTGwzNU11aUJOYXNHWWpI
            YjBZOVVyZlY5U2Q0S2FzNC9PU1BVU2MKiByK9YipngsiQG8ecSXOBfSkpSHGmhe4
            vBYnxfWFXlHOfA9tVkTGIZXs6LhlT7mgzqG6jwfdt9zTdGhJrSgq5w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k3djrwgz90hpanec67jq0dz40apha5rujya9tvn6zdt7mhg9z9gsuy8wrw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOV2piaG5KNUthWTJqd05r
            SHFOdjZON1JPbnVLZXpSSFhiTXhtUmtCekZRCjY0bWo1Z3B6OWVJbzZCV3dQOWl4
            VTJYRksxUitPM3hsWEZ2Z01Xd1hqalEKLS0tIC9JM08yNmhUVEVyVTkzTERGMGow
            MUhjQ1R0Y0s0cGE5Qnp4dC84bDFiRUEKk8LRDAvBmnc1o/ln5UCd9Zr4T1AEnUyx
            6Cg4niyJ5B01r/l2MVjL9E58Iu8CDSJ/mkhihrmVF9+JMYwzfy9MVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-31T17:43:14Z"
    mac: ENC[AES256_GCM,data:+AsCz2p0HNUUJ/3aD9HXs5WjcJk82YShDiypS/KE7+PFpcWsdiiS8Yb01JXr8h3AGr10wp+0VK29ucA08wmG9s4ES0CYN31KpR0XY/D/NeWKpqUAKnyzWC6kA0x5kZSDxVB33lmSlAXbp9N5vzYEk6XFC2gdaigk0zQROBMvg78=,iv:Qj24bbzTGXah95NUyO7bsQK6+BqpwOF36WW+yBSEef4=,tag:ceAz1vlP/0t1uyRhEWF71w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
