apiVersion: helm.cattle.io/v1
kind: HelmChartConfig

metadata:
  name: traefik
  namespace: kube-system

spec:
  failurePolicy: reinstall
  valuesContent: |-
    ports:
      postgres:
        port: 5432
        exposedPort: 5432
        protocol: TCP
        expose:
          default: true

      redis:
        port: 6379
        exposedPort: 6379
        protocol: TCP
        expose:
          default: true

      mqtt:
        port: 1883
        exposedPort: 1883
        protocol: TCP
        expose:
          default: true

      mysql:
        port: 3306
        exposedPort: 3306
        protocol: TCP
        expose:
          default: true
