apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secrets
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:pfgmQSpHy36YAKZwmq/XFlCZaP7IYRs9dnprIljUxb9wnGvKirsb4g==,iv:B/XLahLnabwnpngyKoQPnQKY9SG2GoOBxdEWTC3ewKM=,tag:KDf18VPZmQiqR+aixuZYGQ==,type:str]
sops:
    age:
        - recipient: age1cs0csgzz7xtc644my5r9ee0uy8s6zx3njnymwd32g8rwcamqzges8pds9a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIUFZlOC8vVFFwajhaT3hQ
            VlBma1lDVkZXNHhSbUJEWnZXR3pJVkJRYVJJCnJVUFNTUGNrTGZZQk9XRUZOUTFN
            L0Jka0lRWFZyeDVnRXgrbEcwWVFIVlkKLS0tIGI5dlZlZ2VvaUY1U1hyQkdYTVBn
            SllLOTB1MGVHNGFQTS9UemI4eHUrc2sK1/u8Jn/1MXg90X1AzEwmb+ym1FHzSwCn
            XR6hTpgzow9S7JA2slfU6Lk4a1SJFsuJLLcTJ7FcKEiOy0wbIq3Pmg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cuuzzp3fu0g62hdpgszw4ce9ndpk4zgaxaj8x3s0u00kq9xmnp6qq7547k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYmlsWGViSFEvdmNoWEVP
            amU1MWFmbmJocThqdVlYS0Jqd3BnKy9ZZkdvCkNNMU1SSy9qSFY3T1JHUVZvZmdo
            ckdaZUFrdFdDTkIwZG5FVFpRVWZRRWMKLS0tIHdXKy9GQkpSdkZjNzFyL0NKWkFG
            Qkd4QTVDYUJ2K1JDalNlUmhMSGNCWWMKhcvD1yVAp7B+TZDPADF3UKlIiLCwyCXm
            CaVu/N/mD8E09zi6r+NoUB9M499ADWMBmLuowJTCJpfPFiH+G61Ykw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age179xlc7hrhzlzjatrfjr5a5puldkxqzar7k36409w2dxhh9rxr42q2745tl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxOXdHd2xQRjBZUnFidytB
            Sy9ZRGthdk1lOVBFTHBPWlVLbFY4bER4S0ZRCkk2TVpTQTJFRU9QTTFhWnRmcTBm
            SEovQXRBUEQxQ0VCb0dXU3ZoNEhKSXMKLS0tIGhpNElSYkNoc0tURnZxNDJLMm9T
            UDF3TitxNFNWb0VqUlF1WHArRWN4a2MK5eR3lFwxX2PQfCQMAVqCPimOvAbTgXNe
            jjMfjpYAcqwFu+Mu+347E7K2jtAgGhSJaKYLwMVKCNPrUuc41bcB5A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xk55pvdly05kxl5sxgt4vmczalyw4vmzyrehg5ttqcjz8acvvg5s6nyval
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFRk83RjZXSUhYSy9HeHB4
            N1BQT1o4T1MzbXJjeStSa2c5czhBeTFSbGhRCjBIN3JZU3hXTXByUWpUSjhGN2FJ
            LzkxWmg2dmpPN2w5dHVTSW8zeTNBQmMKLS0tIGpIQ3d2Mnl0MHI3bG1TM1VTc2RE
            OFppV2tpaHVTbG92c3Mrb2s0MHQ1M0UKIAp872I/m/f6Y06vRWpIBvve/Wol/2ko
            vHJ77Kr60chAOPYQ5pHMidSiB3CYFrOAOJXQJBcbSMjxHLsp1twFzw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k3djrwgz90hpanec67jq0dz40apha5rujya9tvn6zdt7mhg9z9gsuy8wrw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiSy8vcFlCdFZXSVRhSjZm
            bm5VcGlaYVd4KzNmQlBKb2ZIODRkK3pYclg4CjlYWTNzVkRYbzZUTUZETUFmcGtx
            bjVhZ3ZZOC9qeW82UzgwbWtpRFQ4NmMKLS0tIDlJWkdzVlRWbVg3Q2xiYnlHRUhw
            cWFaYnY3YmYrMDMyUVJpaXlQdHIvNUUKMa6Aj2IpEUC3SaEO4rydnCCZHfhEYiKU
            g3iSvVPl3sLUW/IxCuUctmJzciXXr+T2lxsfaIpBTBLjNvqjxaOTWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-31T17:43:14Z"
    mac: ENC[AES256_GCM,data:wUYyEe8gk+HQ0SVbGF0dbdfM+5nOtWRWbRj8jj3WRarVyMgN32PKeMwqnIcdDsSph1ivKZdqiP423uogSZcxZ2+231+YC1icJqA2IkemdN0w86WwR1JhEPZdSJbziljKSI+2O1ca2YjUBKuJptROA2w3hWJYTNW0UxfSjJu8fWw=,iv:+D9qNm0ar+kARe6FM4nm4D8SH6+S1VXoN502av+50i4=,tag:KHKI7iFdiXcIQk8Up4dX4Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
