apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secrets
    namespace: external-dns
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:e9ZmbA2hKSD1/EHBzX7aKWMCFAOCEDZxopgmUdsy6fuD8N2Ng+H5Dw==,iv:y7ff+lOclYDf1CFrDtJa+ICmSGjrmDID5rblW5UwP54=,tag:UWxF/v/GBE//jzW6mOuemg==,type:str]
sops:
    age:
        - recipient: age1cs0csgzz7xtc644my5r9ee0uy8s6zx3njnymwd32g8rwcamqzges8pds9a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1M091dnh3VnpvSUpyd3kr
            VkFxS1o0M0hLSnk1dWNEdTRQVTJreEhFNUE4Cm1DbFZHY1dsdkYvSnYxMnljWTJk
            K1BQNlE1cmhnbHZ4UUVUSlFxazNESEkKLS0tIFI0ZE1tVDV5VGtBZWhNbUtlVU90
            UXF0dmVMWG1YbXZGbVRaMmR1L2daaTgK6MTVwMyKEFhQD/dIdTGYGUegOoOckIag
            pKGnuFddn56pnKc4cT/RGx0CS8IXg1ASrG2ffv0g19QjacLaBJhG+Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cuuzzp3fu0g62hdpgszw4ce9ndpk4zgaxaj8x3s0u00kq9xmnp6qq7547k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpejI4L0NqRnpzM1hwY2d6
            a0RLNnFiTGs2aGovLzZRdzdYTFdobnNIN2dFClpOTjBWYjJnOHZMdmFQVm1tbnFG
            THBzYmJ3d2JHUVEybS9pK2l1MGF4WncKLS0tIDI2dnhRYTlxd29YMEs3MzNmenZN
            ODVaUnZMOStWVnEzZkpFTXR6VzBvYncK0Nd1WHJsyB8wSVEk5sHCrgaCa1QDI+fw
            QFv2TQpQAiCzWEOCRu22M55sKhxLoihV58XemjNFrWzoBDi21uOpOA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age179xlc7hrhzlzjatrfjr5a5puldkxqzar7k36409w2dxhh9rxr42q2745tl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwRmM1NGRodDlhM3oxbG1t
            ZUtsZTFXY04vTTlYS2g0aFBEUGRldGRCREhrCkN3ZG5sU0FVMW50Ky9tZjFQdWJD
            VDBJMGhTTTZLVXRwRjBxNm1DQlV2eU0KLS0tIHpiODVKdG5CQXByOURQTXBSajdy
            N09VZFl2WTRuNFRLVjlSMGVDN2N3UW8K9rVdRpm2a46psEr4sMrulGV1SeypMT6r
            +U3ep4oWbTZhhdyy2ux6cec+S2egGPy7ZpKsSpQm7bX4GaF0ZeI4pQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xk55pvdly05kxl5sxgt4vmczalyw4vmzyrehg5ttqcjz8acvvg5s6nyval
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjRzBLN25ndGV1bVJYanAr
            Y3kxc3d3WHViU3M2SlBjQXczVFplMExwaEJNCjdQYXpNUVIvdTI3NktGM25SRElx
            SUZTbjRTQVppQ3hOWnZPQXFPcWJpVTAKLS0tIEQ4Qjl0YzZFR3RBWmpRTEk0OEhE
            NkhDOStYWU1FSFBPeXZ4ZitjWS85UWMKNHpYt8A5Fn4qlOQjeBhbccqst2Pk0RGK
            4yeBxbk0l+O80qP+XbRGDXu/A1cgyizgBRU5kY8zEtnfX64qBCUVgA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k3djrwgz90hpanec67jq0dz40apha5rujya9tvn6zdt7mhg9z9gsuy8wrw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjMWl2ZC9acm51eWU1dkJn
            OU4xQjNEYmoxZG9pZkZtVVRsc2NIaG9laVFVCkpQbW1Pb0xXWEpFM1NlWWw3K294
            SmdsaGlXaDcrRVpPUHk5UEhNTjZuZ28KLS0tIE40THZvbFRKbTEyZzV6MEhrSnd4
            RU9WWHdZYUVCbFcwQ0h3ZUJ5Q1FNQ3cKbtkN7TBcHUZnabE2bk9awilgGev1+SYw
            igQAyYE4ijc1cv5v3I8dH/CxZGNVmcTOfCVo2cGxw0GRBg6L5gcgFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-31T17:43:14Z"
    mac: ENC[AES256_GCM,data:HhHh4mmi/6Yj50gZzr/a5KFtP8+2txzK4nvRyPpngVIMcVapDo0sDZ6YrOQxF+9YkxIC+hiz1F3/9fcRN1B1/IZKsF2jSahTUei45XHLxxIQ8l0T2V/D1ivUEtUB/drhpTlZ0gNHTVGMOeNbvDlt2Txl5CVNsZrC5duzvx4SejM=,iv:SWzLEIkUqeHgJ6x0KOPmkH5sUENcKA00xjAdlKLsIO4=,tag:RGiOPbRI99bVVATrgZeRsA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
