apiVersion: apps/v1
kind: Deployment
metadata:
  name: reaper
  namespace: dev
  labels:
    app: reaper
    app.kubernetes.io/part-of: microphoto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reaper
  template:
    metadata:
      labels:
        app: reaper
    spec:
      containers:
        - name: reaper
          image: ghcr.io/christianmz565/microphoto/reaper:9ccdcea
          ports:
            - name: http
              containerPort: 9092
          envFrom:
            - secretRef:
                name: microphoto-secrets
            - configMapRef:
                name: microphoto-config
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 9092
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 9092
            initialDelaySeconds: 5
            periodSeconds: 5
